apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: aws-networking
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: net.aws.crossplane.lazaroff.pro/v1alpha1
    kind: XAwsNetworking

  writeConnectionSecretsToNamespace: crossplane-system

  patchSets:
  - name: networkconfig
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.clusterName
      toFieldPath: metadata.labels[net.aws.crossplane.lazaroff.pro/network-id]
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.region

  resources:
    ### VPC and InternetGateway
    - name: devops-vcp
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: VPC
        spec:
          forProvider:
            cidrBlock: 10.50.0.0/16
            enableDnsSupport: true
            enableDnsHostnames: true
            tags:
              Owner: DevOps Team 1
              Name: devops-1-crossplane-vpc
      patches:
        - type: PatchSet
          patchSetName: networkconfig
        - fromFieldPath: spec.clusterName
          toFieldPath: metadata.name
        - fromFieldPath: spec.parameters.vpc.cidrBlock
          toFieldPath: spec.forProvider.cidrBlock
         - fromFieldPath: spec.parameters.vpc.tags
          toFieldPath: spec.forProvider.tags

    - name: gateway
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: InternetGateway
        spec:
          forProvider:
            vpcIdSelector:
              matchControllerRef: true
      patches:
        - type: PatchSet
          patchSetName: networkconfig


    ### Subnet Configuration
    - name: subnet-public-eu-central-1a
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            access: public
        spec:
          forProvider:
            mapPublicIpOnLaunch: true
            cidrBlock: 10.50.0.0/24
            vpcIdSelector:
              matchControllerRef: true
            tags:
              created-by: crossplane
      patches:
        - type: PatchSet
          patchSetName: networkconfig
        - fromFieldPath: spec.parameters.subnets.tags
          toFieldPath: spec.forProvider.tags
        - fromFieldPath: spec.parameters.subnets.cidrBlock-az-a
          toFieldPath: spec.forProvider.cidrBlock
        # define eu-central-1a as zone & availabilityZone
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: metadata.labels.zone
          transforms:
            - type: string
              string:
                fmt: "%sa"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.availabilityZone
          transforms:
            - type: string
              string:
                fmt: "%sa"
        # provide the subnetId for later use as status.subnetIds entry
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.subnetIds[0]
    
    - name: subnet-public-eu-central-1b
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            access: public
        spec:
          forProvider:
            mapPublicIpOnLaunch: true
            cidrBlock: 10.50.1.0/24
            vpcIdSelector:
              matchControllerRef: true
            tags:
              created-by: crossplane
      patches:
        - type: PatchSet
          patchSetName: networkconfig
        - fromFieldPath: spec.parameters.subnets.tags
          toFieldPath: spec.forProvider.tags
        - fromFieldPath: spec.parameters.subnets.cidrBlock-az-b
          toFieldPath: spec.forProvider.cidrBlock
          # define eu-central-1b as zone & availabilityZone
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: metadata.labels.zone
          transforms:
            - type: string
              string:
                fmt: "%sb"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.availabilityZone
          transforms:
            - type: string
              string:
                fmt: "%sb"
          # provide the subnetId for later use as status.subnetIds entry
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.subnetIds[1]

    - name: subnet-public-eu-central-1c
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            access: public
        spec:
          forProvider:
            mapPublicIpOnLaunch: true
            cidrBlock: 10.50.2.0/24
            vpcIdSelector:
              matchControllerRef: true
            tags:
              created-by: crossplane
      patches:
        - type: PatchSet
          patchSetName: networkconfig
        - fromFieldPath: spec.parameters.subnets.tags
          toFieldPath: spec.forProvider.tags
        - fromFieldPath: spec.parameters.subnets.cidrBlock-az-c
          toFieldPath: spec.forProvider.cidrBlock
          # define eu-central-1c as zone & availabilityZone
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: metadata.labels.zone
          transforms:
            - type: string
              string:
                fmt: "%sc"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.availabilityZone
          transforms:
            - type: string
              string:
                fmt: "%sc"
          # provide the subnetId for later use as status.subnetIds entry
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.subnetIds[2]  

    ### SecurityGroup & SecurityGroupRules Cluster API server
    - name: securitygroup-cluster
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroup
        metadata:
          labels:
            net.aws.crossplane.lazaroff.pro: securitygroup-cluster
        spec:
          forProvider:
            description: cluster API server access
            name: securitygroup-cluster
            vpcIdSelector:
              matchControllerRef: true
      patches:
        - type: PatchSet
          patchSetName: networkconfig
        - fromFieldPath: spec.clusterName
          toFieldPath: metadata.name
          # provide the securityGroupId for later use as status.securityGroupClusterIds entry
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.securityGroupClusterIds[0]

    - name: securitygrouprule-cluster-inbound
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroupRule
        spec:
          forProvider:
            #description: Allow pods to communicate with the cluster API server & access API server from kubectl clients
            type: ingress
            cidrBlocks:
              - 0.0.0.0/0
            fromPort: 443
            toPort: 443
            protocol: tcp
            securityGroupIdSelector:
              matchLabels:
                net.aws.crossplane.lazaroff.pro: securitygroup-cluster
      patches:
        - type: PatchSet
          patchSetName: networkconfig

    - name: securitygrouprule-cluster-outbound
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroupRule
        spec:
          forProvider:
            description: Allow internet access from the cluster API server
            type: egress
            cidrBlocks: # Destination
              - 0.0.0.0/0
            fromPort: 0
            toPort: 0
            protocol: tcp
            securityGroupIdSelector:
              matchLabels:
                net.aws.crossplane.lazaroff.pro: securitygroup-cluster
      patches:
        - type: PatchSet
          patchSetName: networkconfig

    ### Route, RouteTable & RouteTableAssociations
    - name: route
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Route
        spec:
          forProvider:
            destinationCidrBlock: 0.0.0.0/0
            gatewayIdSelector:
              matchControllerRef: true
            routeTableIdSelector:
              matchControllerRef: true
      patches:
        - type: PatchSet
          patchSetName: networkconfig

    - name: routeTable
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTable
        spec:
          forProvider:
            vpcIdSelector:
              matchControllerRef: true
      patches:
      - type: PatchSet
        patchSetName: networkconfig

    - name: mainRouteTableAssociation
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: MainRouteTableAssociation
        spec:
          forProvider:
            routeTableIdSelector:
              matchControllerRef: true
            vpcIdSelector:
              matchControllerRef: true
      patches:
        - type: PatchSet
          patchSetName: networkconfig

    - name: RouteTableAssociation-public-a
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        spec:
          forProvider:
            routeTableIdSelector:
              matchControllerRef: true
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                access: public
      patches:
        - type: PatchSet
          patchSetName: networkconfig
        # define eu-central-1a as subnetIdSelector.matchLabels.zone
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.subnetIdSelector.matchLabels.zone
          transforms:
            - type: string
              string:
                fmt: "%sa"

    - name: RouteTableAssociation-public-b
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        spec:
          forProvider:
            routeTableIdSelector:
              matchControllerRef: true
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                access: public
      patches:
        - type: PatchSet
          patchSetName: networkconfig
        # define eu-central-1b as subnetIdSelector.matchLabels.zone
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.subnetIdSelector.matchLabels.zone
          transforms:
            - type: string
              string:
                fmt: "%sb"

    - name: RouteTableAssociation-public-c
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        spec:
          forProvider:
            routeTableIdSelector:
              matchControllerRef: true
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                access: public
      patches:
        - type: PatchSet
          patchSetName: networkconfig
        # define eu-central-1c as subnetIdSelector.matchLabels.zone
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.subnetIdSelector.matchLabels.zone
          transforms:
            - type: string
              string:
                fmt: "%sc"