apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata: [originAnnotations]
configMapGenerator:
- name: aws-auth
  namespace: kube-system
  files:
    - mapUsers=mapUsers.yaml
generatorOptions:
  disableNameSuffixHash: true