kind: ExternalSecret
metadata:
  name: fluxui-admin-creds
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: ch4-security-aws  # The secret store name we have created.
  target:
    name: fluxui-admin-creds # Secret name in Kubernetes
  data:
  - secretKey: adminUser # which key it's going to be stored
    remoteRef:
      key: ch4-security # Our AWS secret name goes here
      property: username # AWS Secret key
  - secretKey: adminPassword # which key it's going to be stored
    remoteRef:
      key: ch4-security # Our AWS secret name goes here
      property: password # AWS Secret key 