apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: controlplaneio
  namespace: flux-system
spec:
  interval: 1m0s
  url: oci://ghcr.io/controlplaneio-fluxcd/charts
  type: "oci"