apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  # XRDs must be named 'x<plural>.<group>'
  name: xawsekss.eks.aws.crossplane.lazaroff.pro
spec:
  # This XRD defines an XR in the 'crossplane.lazaroff.pro' API group.
  # The XR or Claim must use this group together with the spec.versions[0].name as it's apiVersion, like this:
  # 'crossplane.lazaroff.pro/v1alpha1'
  group: eks.aws.crossplane.lazaroff.pro
  
  # XR names should always be prefixed with an 'X'
  names:
    kind: XAwsEks
    plural: xawsekss
  # This type of XR offers a claim, which should have the same name without the 'X' prefix
  claimNames:
    kind: AwsEks
    plural: awseks

  defaultCompositionRef:
    name: aws-eks

  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              clusterName:
                type: string
                description: ID of this Cluster that other objects will use to refer to it.
              version:
                type: string
                description: Kubernetes version. Defaults to EKS Cluster Kubernetes version.
              parameters:
                type: object
                description: EKS configuration parameters.
                properties:
                  # Using subnetIds & securityGroupClusterIds from XNetworking to configure VPC
                  subnetIds:
                    type: array
                    items:
                      type: string
                  securityGroupClusterIds:
                    type: array
                    items:
                      type: string
                  region:
                    type: string
                  nodeGroup:
                    type: object
                    description: EKS node configuration parameters.
                    properties:
                      name: 
                        description: NodeGroup name
                        type: string
                      amiType:
                        description: The AMI type for your node group.  Valid values - AL2023_ARM_64_STANDARD, AL2023_X86_64_STANDARD, AL2_ARM_64, AL2_X86_64, BOTTLEROCKET_ARM_64, BOTTLEROCKET_X86_64 etc.
                        type: string
                      capacityType:
                        description: Type of capacity associated with the EKS Node Group. Valid values - ON_DEMAND and SPOT
                        type: string
                      instanceTypes:
                        description: The size of the nodes; small, medium, large
                        type: string
                      diskSize:
                        type: integer
                        description: Disk size in GiB for worker nodes. Defaults to 50 for Windows, 20 all other node groups.
                      nodesMinSize:
                        type: integer
                        description: Min node count, from 1 to 10.
                      nodesDesiredSize:
                        type: integer
                        description: Desired node count, from 1 to 100.
                      nodesMaxSize:
                        type: integer
                        description: Max node count, from 1 to 100.
                      tags:
                        type: object
                        additionalProperties:
                          type: string
                        description: Tags to apply to the NodeGroup.
                    required:
                    - nodesDesiredSize
                    - tags
                required:
                - subnetIds
                - securityGroupClusterIds
                - region
                - nodeGroup
            required:
            - clusterName
            - parameters
          # defining return values
          status:
            type: object
            properties:
              clusterStatus:
                description: The status of the control plane
                type: string
              nodePoolStatus:
                description: The status of the node pool
                type: string