apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xamazonekss.k8s.crossplane.lazaroff.pro
spec:
  group: k8s.crossplane.lazaroff.pro
  names:
    kind: XAmazonEKS
    plural: xamazonekss
  claimNames:
    kind: AmazonEKS
    plural: amazonekss
  connectionSecretKeys:
  - kubeconfig
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
                description: ID of this Cluster that other objects will use to refer to it.
              version:
                type: string
                description: Kubernetes version. Defaults to EKS Cluster Kubernetes version.
              parameters:
                type: object
                description: Cluster configuration parameters.
                properties:
                  region:
                    type: string
                  vpcCidrBlock:
                    type: string
                  nodes:
                    type: object
                    description: Cluster node configuration parameters.
                    properties:
                      amiType:
                        description: The AMI type for your node group.  Valid values - AL2023_ARM_64_STANDARD, AL2023_X86_64_STANDARD, AL2_ARM_64, AL2_X86_64, BOTTLEROCKET_ARM_64, BOTTLEROCKET_X86_64 etc.
                        type: string
                      capacityType:
                        description: Type of capacity associated with the EKS Node Group Valid values - ON_DEMAND and SPOT
                        type: string
                      instanceTypes:
                        description: The size of the nodes; small, medium, large
                        type: string
                      diskSize:
                        type: integer
                        description: Disk size in GiB for worker nodes. Defaults to 50 for Windows, 20 all other node groups.
                      count:
                        type: integer
                        description: Desired node count, from 1 to 100.
                      tags:
                        type: object
                        additionalProperties:
                          type: string
                        description: Tags to apply to the NodeGroup.
                    required:
                    - count
                    - tags
                  subnets:
                    type: object
                    description: VPC Subnets tags and CIDRs Blocks configuration parameters.
                    properties:
                      cidrBlock-1a:
                        type: string
                      cidrBlock-1b:
                        type: string
                      cidrBlock-1c:
                        type: string
                      tags:
                        type: object
                        additionalProperties:
                          type: string
                        description: Tags to apply to the Subnets.
                    required:
                    - tags
                required:
                - region
                - nodes
            required:
            - id
            - parameters
          status:
            type: object
            properties:
              subnetIds:
                type: array
                items:
                  type: string
              securityGroupClusterIds:
                type: array
                items:
                  type: string