apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: flux-system
spec:
  chart:
    spec:
      chart: crossplane
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: flux-system
      version: "1.6.6"
  targetNamespace: crossplane
  interval: 1m0s
  releaseName: crossplane
  maxHistory: 3
  install:
    crds: CreateReplace
    createNamespace: true
    disableWait: true
  upgrade:
    crds: CreateReplace
    disableWait: true
  rollback:
    disableWait: true
  values:
    replicas: 1