apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: flux2
spec:
  rollbackLimit: 3
  forProvider:
    namespace: flux-system
    chart:
      name: flux2
      repository: https://fluxcd-community.github.io/helm-charts
      version: "2.13.0"
  providerConfigRef: 
    name: helm-provider-eks-2

