apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: flux-webui
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: flux-webui
      version: '>=2.2.4'
  interval: 1m0s
  values: # Inline values
    adminUser:
      create: true
    ingress:
      enabled: false
  valuesFrom: # Values reference refer to Secret fluxui-admin-creds
    - kind: Secret
      name: fluxui-admin-creds
      valuesKey: adminPassword
      targetPath: adminUser.passwordHash
    - kind: Secret
      name: fluxui-admin-creds
      valuesKey: adminUser
      targetPath: adminUser.username