# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: provider-kubernetes
#   namespace: crossplane-system
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: provider-kubernetes
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: cluster-admin
# subjects:
# - kind: ServiceAccount
#   name: provider-kubernetes
#   namespace: crossplane-system
# ---
# apiVersion: pkg.crossplane.io/v1beta1
# kind: DeploymentRuntimeConfig
# metadata:
#   name: provider-kubernetes
# spec:
#   serviceAccountTemplate:
#     metadata:
#       name: provider-kubernetes
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.14.1
  # runtimeConfigRef:
  #   name: provider-kubernetes