apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  path: ./ch10/clusters/multi-cluster-crossplane
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 1m0s
  retryInterval: 1m0s
  timeout: 5m0s
  # Enable decryption
  decryption:
    # Use the sops provider
    provider: sops
    secretRef:
      # Reference the new 'sops-age' secret
      name: sops-age