---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ks-sops
  namespace: flux-system
spec:
  dependsOn:
    - name: ks-apps
  path: ./ch10/clusters/multi-cluster-crossplane/resources/sops
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 1m0s
  retryInterval: 1m0s
  timeout: 5m0s