---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ks-eks-2-release-flux2-sync
  namespace: flux-system
spec:
  dependsOn:
    - name: ks-eks-2-release-flux2
  path: ./ch10/clusters/multi-cluster-crossplane/resources/crossplane/clusters/eks-2/releases/flux2-sync
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 1m0s
  retryInterval: 1m0s
  timeout: 5m0s