---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ks-jenkins-eks-1
  namespace: crossplane-system
spec:
  dependsOn:
    - name: ks-crossplane-cluster-1
      namespace: flux-system
  path: ./ch10/apps
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  kubeConfig:
    secretRef:
      name: crossplane-eks-1-access
  healthChecks:
  - apiVersion: k8s.crossplane.lazaroff.pro/v1alpha1
    kind: AmazonEKS
    name: crossplane-eks-1
    namespace: default
  wait: true
  interval: 1m0s
  retryInterval: 1m0s
  timeout: 5m0s