---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgAHwZizQcQ33lWm+esl9eUXF2wCJrLBWoZiRt6T3KukyRnY5mwqtCxr2UIRfNXYK6pcouVEYYmF0vryzfq/+U0WJ3FaI0Pgxhi248Ydihbo8QGIIgqIoh9eYhrC9K68E7rrmP3ySdiKTazkFHp0vvSqvfcUUD5FTqwMNJBy6PXrwluM+Kbi3lzHkJTZPcCwLJ6l9CCXM5M2+dtECi/uFtXmF3nne9rYTFbzLIbykTHU8yFyJXAua9vv+v4YGZuN5uJsSOVr0dSv3bwXdCSS7o41u0Tz1QFXsOMmUkb/eNQDrOMpSs6728rGYK4/OsmxGAmjLBpMQLXRgaIHjCfTXFpZr5F8Kyf0Iz+TdmGgDrmfKBcHRDB6Tk+T3HdAlyz9sdAQhTlmNYotShjrapC1GfxOAKsdNEZCcRRDhZjaI++8vsNZ944dAj6TFENdTL9vqXV2B05HD1OX3cpQli7sbA90l/jP4hlRPew8Qk1yLbzH7K8AIfhmp+K3qhJF2AP+CLRC8vKMc33+6Q/vYlFcMf4rebp4n/qvItEYlVGlCg9d2G2Zp0FEWOZ0OTEGSlwUvsCSxmJzdCPXkvTTnJOO1ghgKUor70RiSCZL6OskVBdyefNXwy/Ehc9oEjflvDR2npV+1Iq8WrCwY/rB0a0nLJ0EFi5Ttti7t4WOsVIVTCqxhYpyhKq8mjkdj/ZBGfXiMHKskF43Qb8o2LI=
    user: AgAvmlvoanqV/faV06HMykaHmFOO0w8C9SKfL8UUKRXAcEZA88bu6ziSd3XGdNDN2a/9+hGdW+KMBgbd+rV6iMyehUkyVHu5PQrp2gb/fkAaOZvUc2FtN4HnMBUfh/gTFzAITTQFHp01K9alJUcjr8sEGkpPC5TYHgPd8WQKFoegauWFtrm06DvRgcNrh9BBXKZyp2080cqHHLZz2Kf6WiXju9ldsbEikF5GDE4pBEsrPKUq+8Sc8yca3v3N7VWJRJBLFu3X2Zjj5WfSnqgtzYzxp0RD0fUJScSuCUcSNOVFr+b+/SL72SYhroAz19U/DsCturTaDZUcKcYKU+qPKT+2vvzHFlISjkOgWYMmtA1GnDWFdRh5c9vPA5wZPPAhLA4kEP4EbWrkFLUNAv27i0XFx8xTHj2iS4QvY+s79zLPfmcQEsge6QOyDOIu8MzA3L4phop2FV80EAAnPfUJFu5Q+yxtU/eNvX7Ki0iskBG3/MgF52NvIz7Sy5z4x+pBRVw0c7VB0NkQOQuQqWOBYPp9u4dJVCHS+eydifdOrpCXTEh2t2xtW44mFcgVgEXusrhYwps1SGcdjBWvvvlezN8hKDNzF5kEZMCmDFtVuk8vXKCntUELGGHRgIPxJ5A6KVC/jCTNdEvChwKz01TKIRhhQuhMt23lRMGLzd3rWmg9W2VgUDMG9FZS3kJCsvs9ckVgFkYBzA==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default