---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jenkins
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.jenkins.io
---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  chart:
    spec:
      chart: jenkins
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
      version: ">=4.0.0"
  interval: 1m
  maxHistory: 3
  install:
    disableWait: true
  upgrade:
    disableWait: true
    cleanupOnFail: true
  rollback:
    disableWait: true
    cleanupOnFail: true
  values:
    controller:
      cloudName: "packt"
      image:
        tagLabel: "lts-jdk17"
      podSecurityContextOverride:
        runAsNonRoot: true
        runAsUser: 1000
        supplementalGroups: [1000]

      javaOpts: >-
        -Xms800m
        -Xmx1800m
        -XX:+UnlockExperimentalVMOptions
        -XX:+UseContainerSupport
        -XX:ActiveProcessorCount=1
        -XX:+UseG1GC
      resources:
        requests:
          cpu: "0.5"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
      ingress:
        enabled: false
        
      installPlugins: []

      markupFormatter:
        rawHtml:
          disableSyntaxHighlighting: false

      JCasC:
        defaultConfig: true
        configScripts:
          welcome-message: |
            jenkins:
              systemMessage: Welcome to our [Packt] GitOps Simplified.
