apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata: [originAnnotations]
configMapGenerator:
- name: aws-auth
  namespace: kube-system
  literals:
    - |
      mapUsers: |
        - groups:
            - system:masters
          userarn: arn:aws:iam::23423423423:user/georgi@example.io
          username: georgi@example.io
generatorOptions:
  disableNameSuffixHash: true