apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ch4-security-aws
  namespace: flux-system
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-creds
            key: aws_access_key_id
          secretAccessKeySecretRef:
            name: aws-creds
            key: aws_secret_access_key