apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  interval: 1m0s
  targetNamespace: linkerd
  releaseName: linkerd-control-plane
  chart:
    spec:
      chart: linkerd-control-plane
      version: '2024.5.1'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: linkerd-edge
  valuesFrom:
    - kind: Secret
      name: linkerd-identity-issuer
      valuesKey: ca.crt
      targetPath: identityTrustAnchorsPEM
    - kind: Secret
      name: linkerd-identity-issuer
      valuesKey: tls.crt
      targetPath: identity.issuer.tls.crtPEM
    - kind: Secret
      name: linkerd-identity-issuer
      valuesKey: tls.key
      targetPath: identity.issuer.tls.keyPEM
  values:
    priorityClassName: "system-cluster-critical"
    identity:
      externalCA: false
      issuer:
        scheme: kubernetes.io/tls