---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-webui-hr
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-webui-secret
  path: ./ch4/clusters/security/infra/flux-webui/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 1m0s
  retryInterval: 1m0s
  timeout: 5m0s