apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
  namespace: terraform
spec:
  interval: 1m
  chart:
    spec:
      chart: tf-controller
      version: '>=0.15.0'
      sourceRef:
        kind: HelmRepository
        name: tofu-controller
        namespace: flux-system
  install:
    crds: Create
    disableWait: true
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    disableWait: true
    remediation:
      retries: -1
  rollback:
    disableWait: true
    recreate: true
    force: true
    cleanupOnFail: true
  uninstall:
    disableWait: true
    keepHistory: false
  maxHistory: 3
  values:
    allowCrossNamespaceRefs: true
    concurrency: 100
    runner:
      grpc:
        maxMessageSize: 1000
      serviceAccount:
        create: true
        name: "tofu-controller-sa"
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::<PUT YOUR AWS ACCOUNT ID>:role/tofu-admin-role