---
apiVersion: k8s.crossplane.lazaroff.pro/v1alpha1
kind: AmazonEKS
metadata:
  namespace: flux-system
  name: crossplane-eks-1
spec:
  clusterName: crossplane-eks-1
  version: "1.30"
  parameters:
    region: eu-central-1
    nodeGroup:
      name: default-node-group-eks-1
      amiType: "AL2_ARM_64"
      capacityType: "SPOT"
      instanceTypes: small
      diskSize: 250
      nodesMinSize: 1
      nodesDesiredSize: 2
      nodesMaxSize: 6
      tags:
       kubernetes.io/cluster/crossplane-eks-1: shared
       Name: crossplane-eks-1
    # mapUsers: |
    #   - groups:
    #     - system:masters
    #     userarn: arn:aws:iam::603782460543:user/georgi.lazarov@nexo.io
    #     username: georgi.lazarov@nexo.io
    vpc:
      cidrBlock: "10.50.0.0/16"
      tags:
        Owner: "DevOps Team A"
        Name: "devops-team-a-crossplane-vpc"
    subnets:
      cidrBlock-az-a: "10.50.0.0/24"
      cidrBlock-az-b: "10.50.1.0/24"
      cidrBlock-az-c: "10.50.2.0/24"
      tags:
        kubernetes.io/cluster/crossplane-eks-1: "owned"
        kubernetes.io/role/elb: "1"
    sg:
      labels:
        net.aws.crossplane.lazaroff.pro: securitygroup-cluster-1
      ruleNames:
        inbound: "securitygrouprule-cluster-1-inbound"
        outbound: "securitygrouprule-cluster-1-outbound"
  writeConnectionSecretToRef:
    name: eks-1-cluster-kubeconfig