---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkerd-smi
  namespace: flux-system
spec:
  dependsOn:
    - name: linkerd-viz
  suspend: false
  path: ./ch6/clusters/flagger/apps/linkerd/linkerd-smi
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 1m0s
  retryInterval: 1m0s
  timeout: 5m0s