apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-ubuntu-pkg-mgmt-tools
spec:
  selector:
    matchLabels:
      app: ubuntu
  process:
    matchPaths:
    - path: /usr/bin/apt
    - path: /usr/bin/apt-get
  action:
    Block