apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: only-allow-bash
spec:
  selector:
    matchLabels:
      app: ubuntu
  file:
    matchDirectories:
    - dir: /
      recursive: true  
  process:
    matchPaths:
    - path: /bin/bash
  action:
    Allow