---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    secretRef:
      key: aws-creds
      name: aws-secret
      namespace: crossplane
    source: Secret