apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  chart:
    spec:
      chart: external-secrets
      version: 0.8.3
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  interval: 10m
  maxHistory: 3
  install:
    disableWait: true
  upgrade:
    disableWait: true
  rollback:
    disableWait: true
  values:
    installCRDs: true