apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flagger-ks
  namespace: flux-system
spec:
  dependsOn:
    - name: linkerd-ks
  path: ./ch6/clusters/flagger/apps/flagger
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 1m0s
  retryInterval: 1m0s
  timeout: 5m0s